dci_interactions/config/routes.rb
Myapp::Application.routes.draw do
  delete 'logout' => 'sessions#destroy'
  get 'login' => 'sessions#new'

  resources :passwords, only: [:create, :edit, :update]
  get 'reset_password' => 'passwords#new'
  put 'update_from_profile' => 'passwords#update_from_profile'

  resources :sessions, only: [:create]

  resources :users, only: [:update]
  get 'profile' => 'users#profile'
  get 'sign_up' => 'users#sign_up'
  put 'register' => 'users#register'
  post 'invite' => 'users#invite'

  resources :sub_accounts, only: [:index, :edit, :update]
  get 'sub_accounts/:id', to: "sub_accounts#edit"

  put 'set_current_sub_account' => 'sub_accounts#set_current'

  resources :sub_account_users, only: [:destroy]

  resources :contacts, only: [:index]
  get 'contacts/import' => 'contacts#import'

  resources :email_templates, except: [:show]

  root 'main#dashboard'
end

dci_interactions/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    @user = user

    can :manage, User, id: @user.id

    if user.account_owner
      can :manage, [SubAccount, SubAccountUser, Contact]
    else
      SubAccountUser::ROLES.each {|role| send(role, role)}
    end
  end

  def sub_account_manager(role)
    can :manage, SubAccount, sub_account_users: {user_id: @user.id, role: role}
    can :read, Contact, sub_account: {sub_account_users: {user_id: @user.id, role: role}}
  end

  def account_owner(role)
    can :manage, Contact, sub_account: {sub_account_users: {user_id: @user.id, role: role}}
    can :invite, SubAccount, sub_account_users: {user_id: @user.id, role: role}
    can :manage, SubAccount, sub_account_users: {user_id: @user.id, role: role}
    can :delete_user, SubAccount, sub_account_users: {user_id: @user.id, role: role}
    can :destroy, SubAccountUser, sub_account:
        {sub_account_users: {user_id: @user.id, role: role}}
  end
end

dci_interactions/app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :email, :source, :email_preference, :status, :sub_account_id, presence: true

  belongs_to :sub_account

  scope :not_deleted, -> { where.not(status: 'deleted') }
  scope :deleted, -> { where(status: 'deleted') }
end

dci_interactions/app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  TIMEZONES = ActiveSupport::TimeZone.all.map(&:name)

  validates :password, length: {minimum: 6}, if: Proc.new { |user| user.password.present? }
  validates :password, presence: true, if: Proc.new { |user| user.persisted? && user.invitation_token.present? ||
                                                             user.new_record? && user.invitation_token.blank?  ||
                                                             user.reset_password_token.present? }
  validates_confirmation_of :password
  validates_presence_of :password_confirmation, if: :password
  validates :email, presence: true, uniqueness: true, format: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :full_name, presence: true, if: Proc.new { |user| user.invitation_token.blank? ||
                                                              user.persisted? && user.invitation_token.present? }
  validates :last_login_from, format: /\b(?:\d{1,3}\.){3}\d{1,3}\b/, allow_blank: true
  validates_inclusion_of :time_zone, in: TIMEZONES
  validates_plausible_phone :phone

  phony_normalize :phone

  has_many :sub_account_users, dependent: :destroy
  has_many :sub_accounts, through: :sub_account_users
  belongs_to :invited_by, class_name: 'User'

  def self.invited_with_token(token)
    includes(:invited_by).where(invitation_token: token).first
  end

  def role_for_sub_account sub_account
    if sub_account_user = sub_account_users.where(sub_account: sub_account).first
      return sub_account_user.role
    end
  end

  def has_role_for_sub_account?(sub_account, role)
    role_for_sub_account(sub_account) == role
  end
end

dci_interactions/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def require_sub_account
    if current_sub_account.nil?
      flash[:error] = 'Please select current Sub Account!'
      redirect_to root_path
    end
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, alert: exception.message
  end

  private

  def not_authenticated
    redirect_to login_url
  end
end

dci_interactions/app/controllers/base_controller.rb
class BaseController < ApplicationController
  include SubAccountConcern
end

dci_interactions/app/controllers/concerns/sub_account_concern.rb
module SubAccountConcern
  extend ActiveSupport::Concern

  def set_current_sub_account(sub_account)
    session['current_sub_account_id'] = sub_account ? sub_account.id : nil
    request.env[:current_sub_account] = sub_account
  end

  def current_sub_account_id
    session["current_sub_account_id"]
  end

  def setup_sub_account
    request.env[:current_sub_account] = if current_sub_account_id
      SubAccount.accessible_by(current_ability).where("sub_accounts.id" => current_sub_account_id).first
    else
      SubAccount.accessible_by(current_ability).first
    end

    if request.env[:current_sub_account] == nil
      session["current_sub_account_id"] = nil
    end
  end

  def current_sub_account
    setup_sub_account if request.env[:current_sub_account] == nil
    request.env[:current_sub_account]
  end
end

dci_interactions/app/controllers/contacts_controller.rb
class ContactsController < BaseController
  before_action :require_login
  before_action :require_sub_account

  def import
    Resque.enqueue(BrontoContactsImport, current_sub_account.id)

    redirect_to(contacts_path, notice: 'Contacts import from Bronto sucessfully started')
  end
end

dci_interactions/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login, except: [:sign_up, :register]
  before_filter :require_signed_out, only: [:sign_up, :register]

  load_and_authorize_resource :user, only: :profile

  def sign_up
    if (@user = User.invited_with_token(params[:token])) && params[:token]
      render :sign_up, layout: 'session'
    else
      redirect_to login_path, alert: 'Token is invalid!'
    end
  end

  def register
    UserRegistrationInteraction.new(params[:user][:id]).register(params[:user].to_hash)
    login(params[:user][:email], params[:user][:password])

    UserLoggerInteraction.new(params[:user][:id]).log(request.remote_ip)
    redirect_to root_path, notice: 'Logged in!'
  rescue InteractionValidationError => e
    flash[:error] = e.error_message
    redirect_to sign_up_path(token: params[:user].try(:[], :token)), layout: 'session'
  end

  def invite
    @sub_account = SubAccount.find(params[:sub_account_id])
    authorize! :invite, @sub_account
    sub_account_users = UserInvitationInteraction.new(current_user.id, params[:sub_account_id])
                                                 .invite(params[:emails], params[:role], params[:message])
    render json: {sub_account_users: sub_account_users.map{ |sub_account_user| sub_account_user.decorate.profile_hash} }
  rescue InteractionValidationError => e
    render json: {error_message: e.error_message}, status: :unprocessable_entity
  end

  def profile
  end

  def update
    UserProfileUpdatingInteraction.new(current_user.id).update(params[:user].to_hash)
    render json: {full_name: params[:user][:full_name]}
  rescue InteractionValidationError => e
    render json: {error_message: e.error_message}, status: :unprocessable_entity
  end

  private

  def require_signed_out
    redirect_to(root_path, alert: 'Please log out before accept invitation.') and return if current_user
  end
end

dci_interactions/app/views/contacts/_contact.html.slim
tr
  td.select             = check_box_tag :contact_id, contact.id, false, class: 'checkbox'
  td.email              = contact.email
  td.source             = contact.source
  td.email_preference   = contact.email_preference
  td.status             = contact.status
  td.messages_count     = contact.messages_count
  td.browsers           = contact.browsers.join(', ')
  td.email_clients      = contact.email_clients.join(', ')
  td.operating_systems  = contact.operating_systems.join(', ')
  td.ip_addresses       = contact.ip_addresses.join(', ')
  td.locations          = contact.decorate.locations
  td.orders_information = contact.decorate.orders_information

dci_interactions/app/views/contacts/index.html.slim
h3
  'All Contacts
  span.badge-big= @all_contacts_count
hr
.col-md-12
  .pull-right
    = link_to 'Import contacts', contacts_import_path, class: 'btn btn-primary'
.clearfix
br
.clearfix

- if @sub_account_contacts.count > 0
  .col-md-12 style='overflow-x: scroll;'
    table#contacts.table.table-striped.table-bordered.table-hover.table-responsive
      thead
        tr
          th.select_all = check_box_tag :select_all, :select_all, false, class: 'checkbox'
          th.email nowrap=true Email
          th.source nowrap=true Source
          th.email_preference nowrap=true Email Preference
          th.status nowrap=true Status
          th.messages_count nowrap=true Messages count
          th.browsers nowrap=true width='90px' Browsers
          th.email_clients nowrap=true Email Clients
          th.operating_systems nowrap=true Operating Systems
          th.ip_addresses nowrap=true IP Addresses
          th.locations nowrap=true width='200px' Locations
          th.orders_information nowrap=true width='200px' Orders Information

      tbody
        = render @contacts
    .clearfix
    #paginator.col-md-12
      .pull-right = paginate(@contacts, window: 2)
  .clearfix
- else
  .bs-callout.bs-callout-warning
    h5 NO CONTACTS FOUND FOR THIS SUB ACCOUNT
    p You can add them by importing, or push via API

dci_interactions/app/views/main/dashboard.html.slim
.span8
  .bs-example
    .bs-callout.bs-callout-warning
      h5 WE HAVEN'T RECEIVED ANY EVENTS FROM YOU YET
      p To make full use of Dashboard you need to start import contacts, create and send messages. After this, we'll
        fill charts and events with appropriate information.
    = image_tag('dashboard_demo.gif', class: 'img-responsive')

dci_interactions/app/views/sub_account_users/_sub_account_user.html.slim
tr
  td = sub_account_user.user.email
  td = sub_account_user.user.full_name
  td = sub_account_user.user.decorate.login_timestamp
  td
    - if user_can_delete
      = link_to 'Delete', sub_account_user_path(sub_account_user), method: :delete, remote: true,
        class: 'delete_user btn btn-danger', data: { confirm: "Are you sure?" }

dci_interactions/app/views/users/profile.html.slim
#profile.row
  h3
    'My profile
    small Change your account information
  hr

  ul#my_profile.nav.nav-tabs
    li.personal.active
      a href='#personal' data-toggle='tab' Personal
    li.security
      a href='#security' data-toggle='tab' Security
    li.settings
      a href='#settings' data-toggle='tab' Settings

  .tab-content
    #personal.tab-pane.active
      .row
        = form_for current_user, method: :put, remote: true, html: { class: 'form-horizontal padding-20' } do |f|
          .form-group
            label.col-md-2.control-label Full name
            .col-md-10
              = f.text_field :full_name, class: 'form-control'
          .form-group
            label.col-md-2.control-label Email
            .col-md-10
              p.form-control-static.form-control= current_user.email
          .form-group
            label.col-md-2.control-label Phone
            .col-md-10
              = f.text_field :phone, class: 'form-control'
          .form-group
            label.col-md-2.control-label IM
            .col-md-10
              = f.text_field :im, class: 'form-control'
          .form-group
            .col-md-12
              .pull-right
                a.reset_form.btn.btn-default.margin-right-20 Reset
                = f.submit 'Save', class: 'btn btn-primary'

    #security.tab-pane
      .row.margin-top-20
        .col-md-6
          h3.margin-0 Change password
          = form_for current_user, url: :update_from_profile, method: :put, remote: true, html: { class: 'form-horizontal padding-20' } do |f|
            .form-group
              label.col-md-6.control-label Current Password
              .col-md-6
                = f.password_field :password, class: 'form-control'
            .form-group
              label.col-md-6.control-label New Password
              .col-md-6
                = f.password_field :new_password, class: 'form-control'
            .form-group
              label.col-md-6.control-label New Password Confirmation
              .col-md-6
                = f.password_field :new_password_confirmation, class: 'form-control'
            .form-group
              .col-md-12
                .pull-right
                  = f.submit 'Change Password', class: 'btn btn-primary'

        .col-md-6.padding-20
          .row
            .col-md-7.text-right.padding-0 Last Login at:
            .col-md-5= current_user.decorate.login_timestamp
          .row
            .col-md-7.text-right.padding-0 Last Login from:
            .col-md-5= current_user.last_login_from

    #settings.tab-pane
      .row
        = form_for current_user, method: :put, remote: true, html: { class: 'form-horizontal padding-20' } do |f|
          .form-group
            label.col-md-2.control-label Time Zone
            .col-md-7
              = f.select :time_zone, time_zone_options_for_select(current_user.time_zone), {}, class: 'form-control'
          .form-group
            label.col-md-2.control-label Time Format
            .col-md-7
              = f.select :time_format, time_formats_for_select, {}, class: 'form-control'
          .form-group
            .col-md-9
              .pull-right
                a.reset_form.btn.btn-default.margin-right-20 Reset
                = f.submit 'Save', class: 'btn btn-primary'

dci_interactions/app/views/users/sign_up.html.slim
.well
  h3 Sign Up
  .alert.alert-success
    'You have accepted the invitation from
    = @user.invited_by.decorate.name_or_email
    |!
  = form_for(@user, url: register_path, method: :put, html: { class: 'form-horizontal', id: :sign_up_form }) do |f|
    = f.hidden_field :id, value: @user.id
    = f.hidden_field :token, value: params[:token]
    .form-group
      label.col-md-4.control-label Email Address
      .col-md-8
        p.form-control-static.form-control= @user.email
    .form-group
      label.col-md-4.control-label Full Name
      .col-md-8
        = f.text_field :full_name, class: 'form-control'
    .form-group
      label.col-md-4.control-label Password
      .col-md-8
        = f.password_field :password, class: 'form-control'
    .form-group
      label.col-md-4.control-label Confirm Password
      .col-md-8
        = f.password_field :password_confirmation, class: 'form-control'
    .form-group
      .col-md-12= submit_tag 'Sign Up', class: 'btn btn-primary pull-right'
  .clearfix